### PR TITLE
`asset.package` is deprecated - fix

### LINKED ISSUE #5: `asset.package` is deprecated
Running the plugin together with parcel ^1.9.4 will yield the following deprecation message:

```
⚠️  `asset.package` is deprecated. Please use `await asset.getPackage()` instead.
```

### PR DESCRIPTION
**Pull request by elwin013**
@apvarun please check and merge if it is ok. :-)

// edit: will fix #5

### CODE REVIEW

**Comment by apvarun** [comment]
The getPackage() function is an asynchronous function and so you will need to use async/await to handle the function call. Calling it directly doesn't give the package.json file content.

**Error in console:** _Please use `await asset.getPackage()` instead._

**Comment by elwin013** [comment]
@apvarun Thank you for checking it and informing me about my stupid mistake. :-) Could you review again?

I've pushed another change - now I'm just resolving promise (`getPackage()`), but also fixed code for parcel 1.8.x (`getPackage()` was introduced in 1.9.x)

**Comment by apvarun** [comment]
Changes look good regarding resolving the promise. But since"_bundler.mainAsset.package.pkgfile_" is still supported, the warning is still present. I guess the parcel version >= 1.9 should be resolved first before other cases.

**Comment by elwin013** [comment]
Well, TIL that `hasOwnProperty` doesn't work if method is defined in prototype (and `getPackage` seems to be defined like this). I've fixed condition - now everything should work ok (checked for 1.9.4, 1.8.0, 1.7.1). :-)

**Comment by elwin013** [comment]
Hello @Tolgor! Thank you for you comment. Could you provide some example to replicate this error? On my side everything is working as mentioned above.

**Comment by Tolgor** [comment]
os: Windows 10
node: v8.11.3
parcel-bundler: v1.9.7

**My local fixes**

Fix on getPackage() Promise await
```
// for parcel-bundler@>=1.9
pkgFile = await bundler.mainBundle.entryAsset.getPackage();
```

Fix on destination resolution (was broken on Windows)
```
const copy = (filepath, relative, filename) => {
    const dest = path.join(bundleDir, path.relative(staticDir, filepath));
    [...]
}
```

**Pull request merged**
