### PR TITLE
Add staticOutDir

### LINKED ISSUE #19: Is it possible to set target folder?
Is it possible to set target folder(s), like:

``
staticPath: {
    "source": "['/source/dir','/source/static']",
    "target": "['/target/dir','/target/static']"
  },
``

in [parcel-plugin-copy](https://www.npmjs.com/package/parcel-plugin-copy)?

### LINKED ISSUE #25: How can i add two static folders and keep the structure in the dist folder?
in the source folder, i have img and tpl folders 
I need these copied as they are, into the dist folder (default output folder), so they'll look like
dist/img/img1.png
dist/tpl/template1.html
etc

Tried several ways, how can i achieve that?
Thanks

### PR DESCRIPTION
**Pull request by stoically**
Resolves #19 
Resolves #25

### CODE REVIEW

**Comment by elwin013** [comment]
Hey @stoically - could you rebase over latest `master` branch? ;-)

**Comment by stoically** [comment]
hey @elwin013, done! :)

**Comment by elwin013** [comment]
@stoically Great! :-) Merging!

**Comment by elwin013** [comment]
@stoically thank you for adding this!

**Comment by simensol** [comment]
I have previously used `	"staticFiles": {
		"staticPath": "static",
		"watcherGlob": "**"
	}` which successfully copied all folders inside `static` to `build/js/`. Since I want the folders inside `static` to be copied to `build/assets`, I have now replaced the setup above with `	"staticFiles": {
		"staticPath": [
			{
				"staticPath": "static",
				"staticOutDir": "assets"
			}
		],
		"watcherGlob": "**"
	}`. However, noting is copied at all when using this setup. Something I have missed?

**Comment by stoically** [comment]
[Tested with your configuration](https://github.com/stoically/parcel-plugin-static-files-copy-test) and works well on my end. Are you sure that your project uses the latest plugin version? If not, we'd need a minimal repro to debug.

**Comment by simensol** [comment]
When using `"staticFiles": { "staticPath": [ { "staticPath": "static", "staticOutDir": "assets" } ], "watcherGlob": "**" }`, the static files are copied to `build/js/assets`. When I replace `"staticOutDir": "assets"` with `"staticOutDir": "../assets"` the static files are copied to `build/assets`. Seems like `staticOutDir` is set relative to the `js` folder inside the build path.

**Comment by stoically** [comment]
`staticOutDir` is supposed to copy files into the given directory relative from the parcel `--out-dir`, so if your `--out-dir` is `build/js`, then that's the expected behavior.

**Comment by simensol** [comment]
Strange, since I am running Parcel using `npx --quiet parcel js/*.js js/**/*.js js/**/**/*.js css/*.scss css/**/*.scss css/**/**/*.scss --out-dir build --no-source-maps --no-hmr`.

**Comment by stoically** [comment]
I see, so the plugin seems to decide [based on the asset entry path](https://github.com/elwin013/parcel-plugin-static-files-copy/blob/6cd4ad574d13a89f5d3aaab2b9f4faad8ebd112a/index.js#L17-L20). Not sure what actually is going on and can't debug further right now - maybe open a new issue with the repro so it doesn't get lost, thanks.

**Comment by stoically** [comment]
@elwin013 If you get the chance, it'd be helpful to know whether it's expected behavior that `build/js` is the `--out-dir` in this case and not `build` like specified from @simensol in the [usage example](https://github.com/elwin013/parcel-plugin-static-files-copy/pull/28#issuecomment-515921699)?

**Comment by powerc9000** [comment]
Is there any update on this. I am running into this problem too.

**Comment by elwin013** [comment]
@powerc9000 @simensol will check that

**Pull request merged**
